// source: entities/job.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var entities_common_pb = require('../entities/common_pb.js');
goog.object.extend(proto, entities_common_pb);
goog.exportSymbol('proto.job.Job', null, global);
goog.exportSymbol('proto.job.JobDetail', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.job.Job = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.job.Job, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.job.Job.displayName = 'proto.job.Job';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.job.JobDetail = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.job.JobDetail.repeatedFields_, null);
};
goog.inherits(proto.job.JobDetail, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.job.JobDetail.displayName = 'proto.job.JobDetail';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.job.Job.prototype.toObject = function(opt_includeInstance) {
  return proto.job.Job.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.job.Job} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.job.Job.toObject = function(includeInstance, msg) {
  var f, obj = {
    jobDetail: (f = msg.getJobDetail()) && proto.job.JobDetail.toObject(includeInstance, f),
    textJob: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.job.Job}
 */
proto.job.Job.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.job.Job;
  return proto.job.Job.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.job.Job} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.job.Job}
 */
proto.job.Job.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.job.JobDetail;
      reader.readMessage(value,proto.job.JobDetail.deserializeBinaryFromReader);
      msg.setJobDetail(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTextJob(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.job.Job.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.job.Job.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.job.Job} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.job.Job.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getJobDetail();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.job.JobDetail.serializeBinaryToWriter
    );
  }
  f = message.getTextJob();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional JobDetail job_detail = 1;
 * @return {?proto.job.JobDetail}
 */
proto.job.Job.prototype.getJobDetail = function() {
  return /** @type{?proto.job.JobDetail} */ (
    jspb.Message.getWrapperField(this, proto.job.JobDetail, 1));
};


/**
 * @param {?proto.job.JobDetail|undefined} value
 * @return {!proto.job.Job} returns this
*/
proto.job.Job.prototype.setJobDetail = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.job.Job} returns this
 */
proto.job.Job.prototype.clearJobDetail = function() {
  return this.setJobDetail(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.job.Job.prototype.hasJobDetail = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string text_job = 2;
 * @return {string}
 */
proto.job.Job.prototype.getTextJob = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.job.Job} returns this
 */
proto.job.Job.prototype.setTextJob = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.job.JobDetail.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.job.JobDetail.prototype.toObject = function(opt_includeInstance) {
  return proto.job.JobDetail.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.job.JobDetail} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.job.JobDetail.toObject = function(includeInstance, msg) {
  var f, obj = {
    education: (f = msg.getEducation()) && entities_common_pb.Education.toObject(includeInstance, f),
    experienceYears: jspb.Message.getFieldWithDefault(msg, 2, 0),
    skillsList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.job.JobDetail}
 */
proto.job.JobDetail.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.job.JobDetail;
  return proto.job.JobDetail.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.job.JobDetail} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.job.JobDetail}
 */
proto.job.JobDetail.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new entities_common_pb.Education;
      reader.readMessage(value,entities_common_pb.Education.deserializeBinaryFromReader);
      msg.setEducation(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setExperienceYears(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addSkills(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.job.JobDetail.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.job.JobDetail.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.job.JobDetail} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.job.JobDetail.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEducation();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      entities_common_pb.Education.serializeBinaryToWriter
    );
  }
  f = message.getExperienceYears();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getSkillsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
};


/**
 * optional common.Education education = 1;
 * @return {?proto.common.Education}
 */
proto.job.JobDetail.prototype.getEducation = function() {
  return /** @type{?proto.common.Education} */ (
    jspb.Message.getWrapperField(this, entities_common_pb.Education, 1));
};


/**
 * @param {?proto.common.Education|undefined} value
 * @return {!proto.job.JobDetail} returns this
*/
proto.job.JobDetail.prototype.setEducation = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.job.JobDetail} returns this
 */
proto.job.JobDetail.prototype.clearEducation = function() {
  return this.setEducation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.job.JobDetail.prototype.hasEducation = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 experience_years = 2;
 * @return {number}
 */
proto.job.JobDetail.prototype.getExperienceYears = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.job.JobDetail} returns this
 */
proto.job.JobDetail.prototype.setExperienceYears = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated string skills = 3;
 * @return {!Array<string>}
 */
proto.job.JobDetail.prototype.getSkillsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.job.JobDetail} returns this
 */
proto.job.JobDetail.prototype.setSkillsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.job.JobDetail} returns this
 */
proto.job.JobDetail.prototype.addSkills = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.job.JobDetail} returns this
 */
proto.job.JobDetail.prototype.clearSkillsList = function() {
  return this.setSkillsList([]);
};


goog.object.extend(exports, proto.job);
